name: Deploy Hugo to Server

on:
  push:
    branches:
      - main  # 或者您用于部署的任何分支

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build
      run: hugo --minify

    - name: Deploy
      run: |
        tar -zcvf public.tar.gz public
        scp -o StrictHostKeyChecking=no public.tar.gz root@149.28.84.44:/www/wwwroot/www.gzpharmacos.com
        ssh user@149.28.84.44 'tar -zxvf /www/wwwroot/www.gzpharmacos.com/public.tar.gz -C /www/wwwroot/www.gzpharmacos.com'
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
