name: Deploy Hugo to Server

on:
  push:
    branches:
      - main  # 或者您用于部署的任何分支

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build
      run: |
           hugo --minify
           tar -zcvf www.gzpharmacos.com.tar.gz public
    
    - name: Installing SSH Client
      run: sudo apt-get install openssh-client

    - name: Set up SSH Key
      run: |  
        mkdir -p ~/.ssh
        echo "${{secrets.DEPLOY_KEY}}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 149.28.84.44 >> ~/.ssh/known_hosts

    - name: Connect to Server and Execute Commands
      run: |
        scp -o StrictHostKeyChecking=no www.gzpharmacos.com.tar.gz root@149.28.84.44:/www/wwwroot
        ssh root@149.28.84.44 "tar -zxvf /www/wwwroot/www.gzpharmacos.com.tar.gz -C /www/wwwroot"
      

